# Generated by Django 3.2.19 on 2023-05-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_numero', models.CharField(max_length=40, unique=True)),
                ('capacidad', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14')], default=1)),
                ('precio_por_noche', models.FloatField()),
                ('camita_bebe', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default=1, max_length=4)),
                ('esta_limpia', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default=1, max_length=4)),
                ('posee_heladera', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default=1, max_length=4)),
                ('posee_aire_acondicionado', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default=1, max_length=4)),
                ('posee_calefaccion', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default=1, max_length=4)),
                ('posee_ventana', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default=1, max_length=4)),
                ('posee_cama_matrimonial', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default=1, max_length=4)),
                ('posee_televisor', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default=1, max_length=4)),
                ('posee_wifi', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default=1, max_length=4)),
                ('jacuzzi', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default=1, max_length=4)),
                ('posee_microondas', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default=1, max_length=4)),
                ('check_out_lates', models.FloatField()),
                ('otro_dato', models.CharField(blank=True, max_length=50, null=True)),
                ('estado_libre', models.ImageField(default='libre.jpg', upload_to='')),
                ('estado_ocupado', models.ImageField(default='ocupado.jpg', upload_to='')),
                ('estado_post_ocupado', models.ImageField(default='despues_del_plazo.jpg', upload_to='')),
                ('libre', models.CharField(default='LIBRE', max_length=10)),
                ('ocupada', models.CharField(default='OCUPADA', max_length=10)),
                ('post_ocupada', models.CharField(default='POST OCUPADA', max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Habitacion',
                'verbose_name_plural': 'Habitaciones',
                'db_table': 'habitaciones',
                'ordering': ['id'],
            },
        ),
    ]
