# Generated by Django 3.0.7 on 2023-04-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='post_ocupada',
            field=models.CharField(default='POST OCUPADA', max_length=15),
        ),
    ]
