# Generated by Django 3.2.19 on 2023-05-11 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitacion', '0002_habitacion_posee_microondas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='nombre_numero',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
