# Generated by Django 3.2.19 on 2023-06-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitacion', '0002_habitacion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='capacidad',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1),
        ),
    ]
