# Generated by Django 3.2.19 on 2023-05-24 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habitacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Huesped',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_responsable', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('edad', models.IntegerField()),
                ('dni', models.CharField(max_length=20)),
                ('demas_huespedes', models.CharField(blank=True, max_length=200, null=True)),
                ('patente_vehiculo', models.CharField(blank=True, max_length=20, null=True)),
                ('modelo_vehiculo', models.CharField(blank=True, max_length=40, null=True)),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Huesped',
                'verbose_name_plural': 'Huespedes',
                'db_table': 'huesped',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateTimeField()),
                ('fecha_salida', models.DateTimeField()),
                ('importe_estadia', models.FloatField()),
                ('importe_otros_gasto', models.FloatField()),
                ('total', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('habitacion', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='habitacion.habitacion')),
                ('huesped', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contrato.huesped')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'db_table': 'contrato',
                'ordering': ['id'],
            },
        ),
    ]
