# Generated by Django 3.0.7 on 2023-05-08 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contrato',
            options={'ordering': ['id'], 'verbose_name': 'Contrato', 'verbose_name_plural': 'Contratos'},
        ),
        migrations.AlterModelTable(
            name='contrato',
            table='contrato',
        ),
    ]
