# Generated by Django 3.2.19 on 2023-05-27 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0002_contrato_late_chack_out'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='late_chack_out',
        ),
    ]
