# Generated by Django 3.2.19 on 2023-06-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0002_alter_huesped_demas_huespedes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huesped',
            name='demas_huespedes',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
