# Generated by Django 3.0.7 on 2023-05-08 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habitacion', '0002_habitacion_posee_microondas'),
        ('contrato', '0002_auto_20230508_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='habitacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='habitacion.Habitacion'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='huesped',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contrato.Huesped'),
        ),
    ]
