# Generated by Django 3.2.19 on 2023-06-29 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0003_alter_huesped_demas_huespedes'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='aumento_total',
            field=models.IntegerField(choices=[(4, '4'), (5, '5'), (10, '10'), (15, '15'), (20, '25'), (30, '30'), (35, '35'), (40, '40'), (45, '45'), (50, '50')], default=0),
        ),
        migrations.AddField(
            model_name='contrato',
            name='descuento_importe_noche',
            field=models.IntegerField(choices=[(5, '5'), (10, '10'), (15, '15'), (20, '20'), (25, '25'), (30, '35'), (40, '40'), (45, '45'), (50, '50'), (55, '55'), (60, '60'), (70, '70')], default=0),
        ),
        migrations.AddField(
            model_name='contrato',
            name='descuento_total_calcularo',
            field=models.IntegerField(choices=[(5, '5'), (10, '10'), (15, '15'), (20, '20'), (25, '25'), (30, '35'), (40, '40'), (45, '45'), (50, '50'), (55, '55'), (60, '60'), (70, '70')], default=0),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='importe_otros_gasto',
            field=models.FloatField(default=0.0),
        ),
    ]
