# Generated by Django 3.2.19 on 2023-06-09 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0003_remove_contrato_late_chack_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
